version: "2.0"
services:
  app:
    image: melopt/perl-carton-base
    working_dir: /app
    command: ["carton", "exec", "plackup", "-p", "3000", "-I", "lib", "-r", "app.pl"]
    restart: always
    volumes:
      - ./:/app
      - local:/app/local
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - "db"
  db:
    restart: always
    build: ./docker/mysql/
    environment:
      MYSQL_DATABASE: "sun_moon"
      MYSQL_ROOT_PASSWORD: "password"
      TZ: "UTC"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./:/app
volumes:
  local:
    driver: local
